# roles/wordpress/tasks/plugins.yml
# Installs plugins from the Wordpress Plugin Directory
---

- name: Download plugins
  get_url:
    url: "https://downloads.wordpress.org/plugin/{{ item.name }}.zip"
    dest: "/tmp/{{ item.name }}.zip"
    force: no
  with_items: "{{ wordpress_plugins }}"
  tags: wordpress

- name: Unpack plugins with version numbers
  unarchive:
    src: "/tmp/{{ item.name }}.{{ item.version }}.zip"
    dest: "{{ wordpress_plugin_directory }}"
    creates: "{{ wordpress_plugin_directory }}/{{ item.name }}/"
    copy: false
  with_items: "{{ wordpress_plugins }}"
  when: item.version is defined
  tags: wordpress
